// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WonderfulStore.Infrastructure;

#nullable disable

namespace WonderfulStore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WonderfulStore.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdPromotion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IdPromotion");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WonderfulStore.Core.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7e77dda-a15f-41d2-8eca-117d61a360ec"),
                            Description = "2 por 1"
                        },
                        new
                        {
                            Id = new Guid("837273cf-8e4e-4786-a978-3c9edbccc68d"),
                            Description = "3 por R$10"
                        });
                });

            modelBuilder.Entity("WonderfulStore.Core.Entities.Product", b =>
                {
                    b.HasOne("WonderfulStore.Core.Entities.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("IdPromotion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("WonderfulStore.Core.Entities.Promotion", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
